version: '3.3'

services:
  web:
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/books
    env_file:
      - ./.env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    restart: always
    image: postgres:13.4-alpine
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes:
       - ./data/db/postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:4.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin